### ISSUE TITLE
Contribute back to Swagger Codegen

### ISSUE THREAD

**Issue by wing328** [niku/swagger-codegen-for-elixirclient#3]
Hi,

That's an excellent Elixir API client generator. I wonder if you can contribute it back to the [Swagger Codegen project](https://github.com/swagger-api/swagger-codegen) as there are developers looking for a Elixir API client.

I'm sure the community will be excited to see an API client generator for Elixir.

Best regards,
William

**Comment by niku** [comment]
Hi,

I'm honored to see your comment.
I have planned to contribute back to Swagger Codegen project.
However I think this elixir client code is under development and still unstable.

Which is a better option?

1. Contribute back to Swagger Codegen project as early and developing in the it's repository
2. Developing in this repository, and contribute back when it will be stable
3. Other

regards

**Comment by wing328** [comment]
@niku I prefer option 1 and we can mark the Elixir API client generator as alpha/beta.

The Swagger Codegen community is very active and will submit PRs for enhancements.

**Comment by niku** [comment]
OK, I'll create a pull request to swagger codegen later.

Thank you ❤️

**Comment by wing328** [comment]
@niku thanks 👍 . Let me know if you need any help.

We'll then add you as the template owner in https://github.com/swagger-api/swagger-codegen#template-creator so that the credit goes back to you.

**Comment by wing328** [comment]
PR merged into master. Thanks for your contribution 👍

**Comment by niku** [comment]
Thanks! 😃
